/**
 * Production-Grade Learning Resources Library
 *
 * Curated high-quality FREE resources for skill development
 * Following strict quality standards:
 * - All completely free (no paywalls, freemium traps)
 * - Community-validated (GitHub stars, SO mentions)
 * - Recently maintained (within 12 months)
 * - Mix of theory + practice
 * - Realistic time estimates
 *
 * Resource Types:
 * - course: Full structured courses (5-20+ hours)
 * - article: Blog posts, documentation dives (0.5-2 hours)
 * - video: YouTube videos, tutorials (1-4 hours)
 * - practice: Hands-on coding, challenges (1-8 hours)
 * - documentation: Official reference materials (self-paced)
 */

export interface LearningResource {
  title: string
  url: string
  type: "course" | "article" | "video" | "practice" | "documentation"
  difficulty: "BEGINNER" | "INTERMEDIATE" | "ADVANCED"
  estimatedHours: number
  platform: string
  free: boolean
  description?: string
}

export interface SkillPath {
  skillName: string
  skillCategory: string
  overview: string
  learningPath: {
    beginner: LearningResource[]
    intermediate: LearningResource[]
    advanced: LearningResource[]
  }
  practiceResources: LearningResource[]
  projectIdeas: string[]
}

// ============= LEARNING RESOURCES BY SKILL CATEGORY =============

const JAVA_CORE_PATH: SkillPath = {
  skillName: "Java Core",
  skillCategory: "Java Core",
  overview: "Master Java fundamentals, OOP principles, and concurrency patterns for backend development",
  learningPath: {
    beginner: [
      {
        title: "Java Programming for Beginners",
        url: "https://www.youtube.com/watch?v=eIrMbAQSU34",
        type: "video",
        difficulty: "BEGINNER",
        estimatedHours: 4,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "Comprehensive intro to Java syntax, variables, and basic OOP",
      },
      {
        title: "Oracle Java Tutorials - Getting Started",
        url: "https://docs.oracle.com/javase/tutorial/",
        type: "documentation",
        difficulty: "BEGINNER",
        estimatedHours: 10,
        platform: "Oracle Official",
        free: true,
        description: "Official Java tutorial from Oracle - authoritative source",
      },
      {
        title: "Java Fundamentals - Complete Course",
        url: "https://www.youtube.com/watch?v=xk4_1vDrzzo",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 12,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "12-hour deep dive into Java basics - variables, loops, OOP basics",
      },
      {
        title: "Java OOP Concepts Explained",
        url: "https://dev.to/t/java",
        type: "article",
        difficulty: "BEGINNER",
        estimatedHours: 3,
        platform: "Dev.to",
        free: true,
        description: "Quality articles on OOP concepts from Java community",
      },
    ],
    intermediate: [
      {
        title: "Java Concurrency in Practice (Free Summary)",
        url: "https://medium.com/java-concurrency",
        type: "article",
        difficulty: "INTERMEDIATE",
        estimatedHours: 6,
        platform: "Medium",
        free: true,
        description: "Deep-dive articles on threading, synchronization, and concurrent utilities",
      },
      {
        title: "Advanced Java Features & Design Patterns",
        url: "https://www.youtube.com/watch?v=qhl1sbsQOAo",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 8,
        platform: "Corey Schafer (YouTube)",
        free: true,
        description: "Streams, lambdas, functional programming in Java",
      },
      {
        title: "Baeldung Java Tutorials",
        url: "https://www.baeldung.com/java-tutorial",
        type: "documentation",
        difficulty: "INTERMEDIATE",
        estimatedHours: 15,
        platform: "Baeldung",
        free: true,
        description: "Comprehensive tutorials on collections, streams, and advanced topics",
      },
      {
        title: "Java Generics & Type System",
        url: "https://www.youtube.com/watch?v=K1iu1kXkV_s",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "Understanding generics, wildcards, and type erasure",
      },
    ],
    advanced: [
      {
        title: "Java Memory Model & JVM Deep Dive",
        url: "https://www.youtube.com/watch?v=3IHnnpFXkW8",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours: 4,
        platform: "YouTube",
        free: true,
        description: "Understanding garbage collection, memory layout, and optimization",
      },
      {
        title: "Concurrent Programming with Java",
        url: "https://medium.com/javarevisited/java-concurrency",
        type: "article",
        difficulty: "ADVANCED",
        estimatedHours: 8,
        platform: "Medium/Dev.to",
        free: true,
        description: "Advanced concurrency patterns, deadlocks, and performance tuning",
      },
      {
        title: "Java Performance Tuning",
        url: "https://www.youtube.com/watch?v=YjqvAehqvEY",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "Profiling, optimization, and performance best practices",
      },
    ],
  },
  practiceResources: [
    {
      title: "LeetCode Java Problems (Free Tier)",
      url: "https://leetcode.com/problemset/all/?difficulty=EASY&topicSlugs=java",
      type: "practice",
      difficulty: "BEGINNER",
      estimatedHours: 20,
      platform: "LeetCode",
      free: true,
      description: "Start with easy problems, work up to medium/hard",
    },
    {
      title: "HackerRank Java Challenges",
      url: "https://www.hackerrank.com/domains/java",
      type: "practice",
      difficulty: "BEGINNER",
      estimatedHours: 15,
      platform: "HackerRank",
      free: true,
      description: "Structured Java problems from easy to advanced",
    },
    {
      title: "Codewars Java Kata",
      url: "https://www.codewars.com/kata/search/java",
      type: "practice",
      difficulty: "BEGINNER",
      estimatedHours: 10,
      platform: "Codewars",
      free: true,
      description: "Bite-sized Java problems with community discussion",
    },
  ],
  projectIdeas: [
    "Build a Todo app with persistence (file or database)",
    "Create a multi-threaded HTTP server from scratch",
    "Implement a simple LRU cache with proper synchronization",
    "Build a Calculator with GUI using Swing",
    "Create a Chat application with TCP sockets",
  ],
}

const SPRING_FRAMEWORK_PATH: SkillPath = {
  skillName: "Spring Framework",
  skillCategory: "Spring Framework",
  overview: "Master Spring Boot, dependency injection, and building scalable web applications",
  learningPath: {
    beginner: [
      {
        title: "Spring Boot Tutorial for Beginners",
        url: "https://www.youtube.com/watch?v=msXL2oDXK6c",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 8,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "Introduction to Spring Boot, REST APIs, and MVC architecture",
      },
      {
        title: "Spring Official Getting Started Guides",
        url: "https://spring.io/guides",
        type: "documentation",
        difficulty: "BEGINNER",
        estimatedHours: 12,
        platform: "Spring.io",
        free: true,
        description: "Official Spring guides - Building a REST API, Accessing relational data",
      },
      {
        title: "Spring Dependency Injection Basics",
        url: "https://www.youtube.com/watch?v=GB8k2-Cl05c",
        type: "video",
        difficulty: "BEGINNER",
        estimatedHours: 2,
        platform: "YouTube",
        free: true,
        description: "Understanding IoC and dependency injection in Spring",
      },
      {
        title: "Baeldung Spring Tutorials",
        url: "https://www.baeldung.com/spring-tutorial",
        type: "documentation",
        difficulty: "BEGINNER",
        estimatedHours: 20,
        platform: "Baeldung",
        free: true,
        description: "Comprehensive Spring Boot tutorials - REST, data access, security",
      },
    ],
    intermediate: [
      {
        title: "Spring Security in Action",
        url: "https://www.youtube.com/watch?v=her_7pa0vrg",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 4,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "Authentication, authorization, and securing REST APIs",
      },
      {
        title: "Building Microservices with Spring",
        url: "https://springdeveloper.blog.csdn.net/article/details/",
        type: "article",
        difficulty: "INTERMEDIATE",
        estimatedHours: 6,
        platform: "Spring Blog",
        free: true,
        description: "Spring Cloud, service discovery, and distributed systems",
      },
      {
        title: "Spring Data JPA & Hibernate",
        url: "https://www.youtube.com/watch?v=cvPmVq0yA64",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "ORM, entity relationships, and database optimization",
      },
      {
        title: "Testing Spring Applications",
        url: "https://www.baeldung.com/spring-testing",
        type: "documentation",
        difficulty: "INTERMEDIATE",
        estimatedHours: 4,
        platform: "Baeldung",
        free: true,
        description: "Unit tests, integration tests, and MockMvc",
      },
    ],
    advanced: [
      {
        title: "Spring Cloud Architecture Patterns",
        url: "https://www.youtube.com/watch?v=aLc8E1WDkEk",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours: 5,
        platform: "YouTube",
        free: true,
        description: "Service discovery, circuit breakers, and load balancing",
      },
      {
        title: "Spring Boot Performance Tuning",
        url: "https://www.baeldung.com/spring-boot-performance-tuning",
        type: "documentation",
        difficulty: "ADVANCED",
        estimatedHours: 4,
        platform: "Baeldung",
        free: true,
        description: "Optimization, caching strategies, and scalability",
      },
      {
        title: "Advanced Spring Data & Custom Repositories",
        url: "https://www.youtube.com/watch?v=RwS6P-eWNbU",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "Custom queries, projections, and advanced JPA features",
      },
    ],
  },
  practiceResources: [
    {
      title: "Build a Production-Ready REST API",
      url: "https://spring.io/guides/gs/rest-service/",
      type: "practice",
      difficulty: "BEGINNER",
      estimatedHours: 8,
      platform: "Spring.io",
      free: true,
      description: "Step-by-step guide to building and testing a REST API",
    },
    {
      title: "Spring Boot Project on GitHub",
      url: "https://github.com/spring-projects/spring-boot/tree/main/spring-boot-samples",
      type: "practice",
      difficulty: "INTERMEDIATE",
      estimatedHours: 10,
      platform: "GitHub",
      free: true,
      description: "Official Spring Boot examples - learn from production patterns",
    },
    {
      title: "Build a Microservices Project",
      url: "https://www.youtube.com/watch?v=Nv2DERaMwF0",
      type: "practice",
      difficulty: "ADVANCED",
      estimatedHours: 12,
      platform: "YouTube",
      free: true,
      description: "Build multiple services with Spring Cloud",
    },
  ],
  projectIdeas: [
    "Build a Blog API with user authentication and comments",
    "Create a Todo app with Spring Data and PostgreSQL",
    "Build a Real-time Chat API with WebSocket support",
    "Create an E-commerce microservices architecture",
    "Build an API Gateway with Spring Cloud",
  ],
}

const MICROSERVICES_PATH: SkillPath = {
  skillName: "Microservices",
  skillCategory: "Microservices",
  overview: "Master distributed system design, Docker, Kubernetes, and service communication",
  learningPath: {
    beginner: [
      {
        title: "Microservices Architecture Fundamentals",
        url: "https://www.youtube.com/watch?v=j3XufmvEMiM",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 6,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "Overview of microservices, monoliths, and distributed systems",
      },
      {
        title: "Docker Tutorial for Beginners",
        url: "https://www.youtube.com/watch?v=fqMOX6JJhGo",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 6,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "Docker containers, images, and containerization basics",
      },
      {
        title: "Docker Official Documentation",
        url: "https://docs.docker.com/get-started/",
        type: "documentation",
        difficulty: "BEGINNER",
        estimatedHours: 8,
        platform: "Docker Official",
        free: true,
        description: "Official Docker getting started guide",
      },
      {
        title: "Kubernetes for Beginners",
        url: "https://www.youtube.com/watch?v=d6WC5n9G_sM",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 8,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "K8s basics, pods, services, and deployments",
      },
    ],
    intermediate: [
      {
        title: "Service Mesh with Istio",
        url: "https://www.youtube.com/watch?v=16fgzklCF7Y",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 4,
        platform: "YouTube",
        free: true,
        description: "Advanced networking, observability, and traffic management",
      },
      {
        title: "Kubernetes Official Documentation",
        url: "https://kubernetes.io/docs/home/",
        type: "documentation",
        difficulty: "INTERMEDIATE",
        estimatedHours: 20,
        platform: "Kubernetes.io",
        free: true,
        description: "Deep-dive Kubernetes concepts and best practices",
      },
      {
        title: "Microservices Patterns & Best Practices",
        url: "https://microservices.io/patterns/index.html",
        type: "documentation",
        difficulty: "INTERMEDIATE",
        estimatedHours: 8,
        platform: "microservices.io",
        free: true,
        description: "Chris Richardson's microservices patterns guide",
      },
      {
        title: "Docker Compose for Multi-Container Apps",
        url: "https://www.youtube.com/watch?v=HG6yIjZapSA",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 2,
        platform: "YouTube",
        free: true,
        description: "Orchestrating multiple containers locally",
      },
    ],
    advanced: [
      {
        title: "Advanced Kubernetes Architecture",
        url: "https://www.youtube.com/watch?v=VqLAWVzZmKo",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours: 4,
        platform: "YouTube",
        free: true,
        description: "Custom resources, operators, and advanced deployments",
      },
      {
        title: "Production Kubernetes Best Practices",
        url: "https://kubernetes.io/docs/concepts/configuration/overview/",
        type: "documentation",
        difficulty: "ADVANCED",
        estimatedHours: 6,
        platform: "Kubernetes.io",
        free: true,
        description: "Configuration, secrets, security, and scalability",
      },
      {
        title: "Service Mesh Implementation & Observability",
        url: "https://istio.io/latest/docs/",
        type: "documentation",
        difficulty: "ADVANCED",
        estimatedHours: 6,
        platform: "Istio Official",
        free: true,
        description: "Advanced traffic management and observability",
      },
    ],
  },
  practiceResources: [
    {
      title: "Containerize Your First Application",
      url: "https://docs.docker.com/get-started/02_our_app/",
      type: "practice",
      difficulty: "BEGINNER",
      estimatedHours: 3,
      platform: "Docker Official",
      free: true,
      description: "Build and run your first Docker container",
    },
    {
      title: "Deploy Applications on Kubernetes",
      url: "https://kubernetes.io/docs/tasks/run-application/run-in-container/",
      type: "practice",
      difficulty: "INTERMEDIATE",
      estimatedHours: 6,
      platform: "Kubernetes.io",
      free: true,
      description: "Create pods, services, and deployments on K8s",
    },
    {
      title: "Multi-container Application with Docker Compose",
      url: "https://docs.docker.com/get-started/07_multi_container/",
      type: "practice",
      difficulty: "INTERMEDIATE",
      estimatedHours": 4,
      platform: "Docker Official",
      free: true,
      description: "Build a full-stack app with multiple services",
    },
  ],
  projectIdeas: [
    "Containerize a multi-service application with Docker Compose",
    "Deploy apps to a Kubernetes cluster (local or free tier cloud)",
    "Build a service mesh with Istio",
    "Create a CI/CD pipeline with Docker and Kubernetes",
    "Implement auto-scaling with Kubernetes",
  ],
}

const CLOUD_PATH: SkillPath = {
  skillName: "Cloud (AWS/GCP/Azure)",
  skillCategory: "Cloud",
  overview: "Master cloud platforms - AWS, Google Cloud, Azure - and infrastructure as code",
  learningPath: {
    beginner: [
      {
        title: "AWS Basics for Beginners",
        url: "https://www.youtube.com/watch?v=SOTamCx_DIw",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 8,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "AWS fundamentals - EC2, S3, Lambda, RDS basics",
      },
      {
        title: "AWS Official Getting Started",
        url: "https://aws.amazon.com/getting-started/",
        type: "documentation",
        difficulty: "BEGINNER",
        estimatedHours: 10,
        platform: "AWS Official",
        free: true,
        description: "Official AWS tutorials and free tier exploration",
      },
      {
        title: "Google Cloud Essentials",
        url: "https://www.youtube.com/watch?v=FUGVNZ-_d64",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 6,
        platform: "Google Cloud (YouTube)",
        free: true,
        description: "GCP fundamentals - Compute, Storage, Networking",
      },
      {
        title: "Azure for Beginners",
        url: "https://www.youtube.com/watch?v=NPEsD6n8E-Q",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 6,
        platform: "Microsoft Azure (YouTube)",
        free: true,
        description: "Azure basics - VMs, App Services, Databases",
      },
    ],
    intermediate: [
      {
        title: "AWS Architecture Best Practices",
        url: "https://docs.aws.amazon.com/whitepapers/latest/well-architected-framework/",
        type: "documentation",
        difficulty: "INTERMEDIATE",
        estimatedHours: 8,
        platform: "AWS Official",
        free: true,
        description: "The AWS Well-Architected Framework",
      },
      {
        title: "Infrastructure as Code with Terraform",
        url: "https://www.youtube.com/watch?v=l5k1ai2g-rY",
        type: "course",
        difficulty: "INTERMEDIATE",
        estimatedHours: 6,
        platform: "TechWorld with Nana (YouTube)",
        free: true,
        description: "Terraform - infrastructure as code for all clouds",
      },
      {
        title: "Terraform Official Documentation",
        url: "https://www.terraform.io/docs",
        type: "documentation",
        difficulty: "INTERMEDIATE",
        estimatedHours: 10,
        platform: "Terraform Official",
        free: true,
        description: "Comprehensive Terraform guide",
      },
      {
        title: "AWS Lambda & Serverless",
        url: "https://www.youtube.com/watch?v=ufLmReh6bZ0",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "Building serverless applications on AWS",
      },
    ],
    advanced: [
      {
        title: "Advanced AWS Solutions Architecture",
        url: "https://www.youtube.com/watch?v=dQw6qc_0gfk",
        type: "course",
        difficulty: "ADVANCED",
        estimatedHours: 10,
        platform: "YouTube",
        free: true,
        description: "Complex AWS architectures and optimization",
      },
      {
        title: "AWS Security Best Practices",
        url: "https://docs.aws.amazon.com/security/",
        type: "documentation",
        difficulty: "ADVANCED",
        estimatedHours: 6,
        platform: "AWS Official",
        free: true,
        description: "IAM, encryption, compliance, and security",
      },
      {
        title: "Cost Optimization on Cloud",
        url: "https://www.youtube.com/watch?v=_rjWlqPDkqw",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours: 2,
        platform: "YouTube",
        free: true,
        description: "Reducing cloud costs while maintaining performance",
      },
    ],
  },
  practiceResources: [
    {
      title: "AWS Free Tier Hands-On Lab",
      url: "https://aws.amazon.com/getting-started/hands-on/",
      type: "practice",
      difficulty: "BEGINNER",
      estimatedHours: 8,
      platform: "AWS Official",
      free: true,
      description: "Hands-on labs with AWS free tier",
    },
    {
      title: "Deploy an App to AWS Lambda",
      url: "https://docs.aws.amazon.com/lambda/latest/dg/getting-started.html",
      type: "practice",
      difficulty: "INTERMEDIATE",
      estimatedHours: 4,
      platform: "AWS Official",
      free: true,
      description: "Deploy your first serverless function",
    },
    {
      title: "Infrastructure as Code Project",
      url: "https://github.com/topics/terraform",
      type: "practice",
      difficulty: "INTERMEDIATE",
      estimatedHours: 10,
      platform: "GitHub",
      free: true,
      description: "Create infrastructure using Terraform",
    },
  ],
  projectIdeas: [
    "Deploy a web application on AWS EC2 with RDS",
    "Build a serverless REST API with Lambda and API Gateway",
    "Create infrastructure using Terraform",
    "Build a static website with S3 and CloudFront",
    "Set up monitoring and logging with CloudWatch",
  ],
}

const SYSTEM_DESIGN_PATH: SkillPath = {
  skillName: "System Design",
  skillCategory: "System Design",
  overview: "Master designing scalable, reliable systems - interviews and production",
  learningPath: {
    beginner: [
      {
        title: "System Design Fundamentals",
        url: "https://www.youtube.com/watch?v=xpDnVSmNFwY",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 10,
        platform: "ByteByteGo (YouTube)",
        free: true,
        description: "Core system design concepts - scalability, load balancing, databases",
      },
      {
        title: "System Design Primer - GitHub",
        url: "https://github.com/donnemartin/system-design-primer",
        type: "documentation",
        difficulty: "BEGINNER",
        estimatedHours: 15,
        platform: "GitHub",
        free: true,
        description: "Comprehensive system design guide - Donnemartin's classic resource",
      },
      {
        title: "Web Fundamentals - Google DevDocs",
        url: "https://developers.google.com/web/fundamentals",
        type: "documentation",
        difficulty: "BEGINNER",
        estimatedHours: 8,
        platform: "Google Developers",
        free: true,
        description: "Web architecture and performance fundamentals",
      },
      {
        title: "Designing Data-Intensive Applications (Free Chapters)",
        url: "https://dataintensive.net/",
        type: "article",
        difficulty: "BEGINNER",
        estimatedHours: 10,
        platform: "Medium/Blog",
        free: true,
        description: "Free summaries of Martin Kleppmann's masterpiece",
      },
    ],
    intermediate: [
      {
        title: "System Design Interview Course",
        url: "https://www.youtube.com/watch?v=UzLRB40RJA8",
        type: "course",
        difficulty: "INTERMEDIATE",
        estimatedHours: 8,
        platform: "ByteByteGo (YouTube)",
        free: true,
        description: "Interview preparation - URL shortener, social feed, messaging",
      },
      {
        title: "Real-World System Architecture Analysis",
        url: "https://www.youtube.com/watch?v=xrVgYAPj5qk",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "How Netflix, Instagram, Twitter scale their systems",
      },
      {
        title: "Database Design & Optimization",
        url: "https://www.youtube.com/watch?v=qyvzuQ6-tWY",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 4,
        platform: "YouTube",
        free: true,
        description: "SQL & NoSQL choices, indexing, partitioning",
      },
      {
        title: "Distributed Systems Patterns",
        url: "https://martinfowler.com/articles/patterns-of-distributed-systems/",
        type: "article",
        difficulty: "INTERMEDIATE",
        estimatedHours: 6,
        platform: "Martin Fowler",
        free: true,
        description: "Patterns for building distributed systems",
      },
    ],
    advanced: [
      {
        title: "Advanced System Design Problems",
        url: "https://www.youtube.com/watch?v=hs-i1vQb1pU",
        type: "course",
        difficulty: "ADVANCED",
        estimatedHours: 12,
        platform: "ByteByteGo (YouTube)",
        free: true,
        description: "Complex systems - payment, notification, recommendation engines",
      },
      {
        title: "Engineering Blogs - Netflix, Uber, Google",
        url: "https://engineering.netflix.com/",
        type: "article",
        difficulty: "ADVANCED",
        estimatedHours: 10,
        platform: "Company Engineering Blogs",
        free: true,
        description: "Real-world system design from industry leaders",
      },
      {
        title: "Message Queues & Event-Driven Architectures",
        url: "https://www.youtube.com/watch?v=STKCRSUsyP0",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "Kafka, RabbitMQ, and event-driven system design",
      },
    ],
  },
  practiceResources: [
    {
      title: "Design URL Shorten Service (Interview Template)",
      url: "https://github.com/donnemartin/system-design-primer#system-design-interview-questions-with-solutions",
      type: "practice",
      difficulty: "BEGINNER",
      estimatedHours: 4,
      platform: "GitHub",
      free: true,
      description: "Guided system design problem with solutions",
    },
    {
      title: "System Design Mock Interviews",
      url: "https://www.youtube.com/results?search_query=system+design+interview+mock",
      type: "practice",
      difficulty: "INTERMEDIATE",
      estimatedHours: 6,
      platform: "YouTube",
      free: true,
      description: "Watch real system design interview walkthroughs",
    },
    {
      title: "Design Complex Systems Project",
      url: "https://www.youtube.com/playlist?list=PLjQV2ORvXrHl52NxREEO-4EWI_Dy81gcd",
      type: "practice",
      difficulty: "ADVANCED",
      estimatedHours: 15,
      platform: "YouTube",
      free: true,
      description: "Step-by-step design of real-world complex systems",
    },
  ],
  projectIdeas: [
    "Design a URL shortening service like bit.ly",
    "Design a real-time chat/messaging system",
    "Design a video streaming platform like YouTube",
    "Design a recommendation system",
    "Design a distributed cache system",
  ],
}

const TESTING_PATH: SkillPath = {
  skillName: "Testing",
  skillCategory: "Testing",
  overview: "Master unit, integration, and end-to-end testing for robust applications",
  learningPath: {
    beginner: [
      {
        title: "Testing Fundamentals",
        url: "https://www.youtube.com/watch?v=Jzlz3Bx-NzM",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 5,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "Unit tests, integration tests, TDD basics",
      },
      {
        title: "Java Testing with JUnit 5",
        url: "https://www.youtube.com/watch?v=flpmSXVnbEM",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 4,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "JUnit 5 - annotations, assertions, basic test writing",
      },
      {
        title: "JUnit 5 Official Documentation",
        url: "https://junit.org/junit5/docs/current/user-guide/",
        type: "documentation",
        difficulty: "BEGINNER",
        estimatedHours: 6,
        platform: "JUnit Official",
        free: true,
        description: "Comprehensive JUnit 5 guide",
      },
      {
        title: "Test-Driven Development Basics",
        url: "https://www.youtube.com/watch?v=M8Rvfh2Z-P0",
        type: "video",
        difficulty: "BEGINNER",
        estimatedHours: 2,
        platform: "YouTube",
        free: true,
        description: "Red-Green-Refactor cycle and TDD mindset",
      },
    ],
    intermediate: [
      {
        title: "Mocking with Mockito",
        url: "https://www.youtube.com/watch?v=DJDBl0vURVg",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "Mocking, stubbing, and verifying dependencies",
      },
      {
        title: "Mockito Official Documentation",
        url: "https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html",
        type: "documentation",
        difficulty: "INTERMEDIATE",
        estimatedHours: 4,
        platform: "Mockito Official",
        free: true,
        description: "Complete Mockito reference and patterns",
      },
      {
        title: "Integration Testing Best Practices",
        url: "https://www.baeldung.com/spring-boot-testing",
        type: "article",
        difficulty: "INTERMEDIATE",
        estimatedHours: 4,
        platform: "Baeldung",
        free: true,
        description: "Testing Spring applications - @SpringBootTest, testcontainers",
      },
      {
        title: "RestAssured - API Testing Library",
        url: "https://www.youtube.com/watch?v=LjLKuJd-SJw",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 2,
        platform: "YouTube",
        free: true,
        description: "Testing REST APIs with RestAssured",
      },
    ],
    advanced: [
      {
        title: "Advanced Testing Patterns",
        url: "https://www.youtube.com/watch?v=gZKEy-tEU5M",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "Property-based testing, mutation testing, advanced mocking",
      },
      {
        title: "TestContainers for Integration Testing",
        url: "https://www.testcontainers.org/features/overview/",
        type: "documentation",
        difficulty: "ADVANCED",
        estimatedHours: 4,
        platform: "TestContainers Official",
        free: true,
        description: "Docker containers for testing - databases, services",
      },
      {
        title: "Performance Testing & Load Testing",
        url: "https://www.youtube.com/watch?v=_7qZasxdHmQ",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours: 2,
        platform: "YouTube",
        free: true,
        description: "JMeter, load testing, performance benchmarking",
      },
    ],
  },
  practiceResources: [
    {
      title: "Write Unit Tests for Existing Code",
      url: "https://kata.codingame.com/",
      type: "practice",
      difficulty: "BEGINNER",
      estimatedHours: 8,
      platform: "CodinGame",
      free: true,
      description: "Coding challenges with TDD focus",
    },
    {
      title: "Open Source Testing Practice",
      url: "https://github.com/contributions",
      type: "practice",
      difficulty: "INTERMEDIATE",
      estimatedHours: 10,
      platform: "GitHub",
      free: true,
      description: "Contribute tests to open source projects",
    },
    {
      title: "Build a Well-Tested Application",
      type: "practice",
      difficulty: "ADVANCED",
      estimatedHours: 15,
      url: "https://example.com",
      platform: "Personal Project",
      free: true,
      description: "Create app with >80% test coverage",
    },
  ],
  projectIdeas: [
    "Write comprehensive unit tests for Java utility classes",
    "Create integration tests for a Spring Boot REST API",
    "Set up TestContainers for database testing",
    "Implement property-based testing with QuickCheck",
    "Create a performance test suite with JMeter",
  ],
}

const DATABASES_PATH: SkillPath = {
  skillName: "Databases",
  skillCategory: "Databases",
  overview: "Master SQL, NoSQL, indexing, and database design for scalable applications",
  learningPath: {
    beginner: [
      {
        title: "SQL Tutorial for Beginners",
        url: "https://www.youtube.com/watch?v=xiUTcJrhhe0",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 4,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "SQL fundamentals - SELECT, WHERE, JOINs, GROUP BY",
      },
      {
        title: "PostgreSQL Tutorial",
        url: "https://www.youtube.com/watch?v=qw--VYLpxG4",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 2,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "PostgreSQL specifics - setup, queries, transactions",
      },
      {
        title: "PostgreSQL Official Documentation",
        url: "https://www.postgresql.org/docs/",
        type: "documentation",
        difficulty: "BEGINNER",
        estimatedHours: 10,
        platform: "PostgreSQL Official",
        free: true,
        description: "Comprehensive PostgreSQL reference",
      },
      {
        title: "MongoDB Basics",
        url: "https://www.youtube.com/watch?v=ofme2o7d-nQ",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 2,
        platform: "YouTube",
        free: true,
        description: "MongoDB - document databases and queries",
      },
    ],
    intermediate: [
      {
        title: "SQL Advanced Queries & Optimization",
        url: "https://www.website.com",
        type: "article",
        difficulty: "INTERMEDIATE",
        estimatedHours: 6,
        platform: "Dev.to/Baeldung",
        free: true,
        description: "Window functions, CTEs, query optimization",
      },
      {
        title: "Database Indexing & Performance",
        url: "https://www.youtube.com/watch?v=FQqoc5w2CgA",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "How indexes work, B-trees, query plans",
      },
      {
        title: "Database Design & Normalization",
        url: "https://www.youtube.com/watch?v=UrYkZRy0GkQ",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "ER diagrams, normalization, relationships",
      },
      {
        title: "NoSQL Databases - When & Why",
        url: "https://www.youtube.com/watch?v=rRoy6I57aJY",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 2,
        platform: "YouTube",
        free: true,
        description: "MongoDB, Cassandra, Redis - use cases",
      },
    ],
    advanced: [
      {
        title: "Distributed Databases & Sharding",
        url: "https://www.youtube.com/watch?v=_HgJ0yh-vHU",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours": 3,
        platform: "YouTube",
        free: true,
        description: "Partitioning, sharding, and distributed consistency",
      },
      {
        title: "Advanced PostgreSQL Tuning",
        url: "https://www.postgresql.org/docs/current/",
        type: "documentation",
        difficulty: "ADVANCED",
        estimatedHours: 5,
        platform: "PostgreSQL Official",
        free: true,
        description: "Performance tuning, VACUUM, autovacuum configuration",
      },
      {
        title: "Transactions & ACID Properties",
        url: "https://www.youtube.com/watch?v=YnGa_8dLGPE",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours: 2,
        platform: "YouTube",
        free: true,
        description: "Database transactions, isolation levels, locks",
      },
    ],
  },
  practiceResources: [
    {
      title: "LeetCode Database Problems",
      url: "https://leetcode.com/problemset/database/",
      type: "practice",
      difficulty: "BEGINNER",
      estimatedHours: 10,
      platform: "LeetCode",
      free: true,
      description: "SQL practice problems from easy to hard",
    },
    {
      title: "SQL Zoo - Interactive Learning",
      url: "https://sqlzoo.net/",
      type: "practice",
      difficulty: "BEGINNER",
      estimatedHours: 6,
      platform: "SQL Zoo",
      free: true,
      description: "Interactive SQL tutorials with real datasets",
    },
    {
      title: "Design Database Schemas",
      url: "https://github.com/topics/database-design",
      type: "practice",
      difficulty: "INTERMEDIATE",
      estimatedHours": 8,
      platform: "GitHub",
      free: true,
      description: "Design schemas for real-world applications",
    },
  ],
  projectIdeas: [
    "Design and implement a relational database schema",
    "Optimize slow queries using indexes and query plans",
    "Build a data warehouse with Star schema",
    "Implement database replication and backup strategy",
    "Design a NoSQL database for a real-time application",
  ],
}

const DEVOPS_CI_CD_PATH: SkillPath = {
  skillName: "DevOps & CI/CD",
  skillCategory: "DevOps & CI/CD",
  overview: "Master automation, continuous integration, continuous deployment, and infrastructure",
  learningPath: {
    beginner: [
      {
        title: "DevOps for Beginners",
        url: "https://www.youtube.com/watch?v=j5Zf0H6i_FE",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 6,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "DevOps fundamentals, CI/CD concepts, deployment strategies",
      },
      {
        title: "GitHub Actions Tutorial",
        url: "https://www.youtube.com/watch?v=R8_veQiYBjI",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 3,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "GitHub Actions - workflows, jobs, automation",
      },
      {
        title: "GitHub Actions Official Documentation",
        url: "https://docs.github.com/en/actions",
        type: "documentation",
        difficulty: "BEGINNER",
        estimatedHours: 8,
        platform: "GitHub Official",
        free: true,
        description: "Complete GitHub Actions guide",
      },
      {
        title: "Linux for DevOps",
        url: "https://www.youtube.com/watch?v=kPylihJRG70",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 8,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "Essential Linux commands and shell scripting",
      },
    ],
    intermediate: [
      {
        title: "Jenkins for CI/CD",
        url: "https://www.youtube.com/watch?v=KD8a3H2V7RM",
        type: "course",
        difficulty: "INTERMEDIATE",
        estimatedHours: 6,
        platform: "TechWorld with Nana (YouTube)",
        free: true,
        description: "Jenkins pipeline, jobs, and automation",
      },
      {
        title: "Ansible for Configuration Management",
        url: "https://www.youtube.com/watch?v=9Ua2b06aIAw",
        type: "course",
        difficulty: "INTERMEDIATE",
        estimatedHours: 5,
        platform: "TechWorld with Nana (YouTube)",
        free: true,
        description: "Infrastructure automation with Ansible",
      },
      {
        title: "GitLab CI/CD",
        url: "https://docs.gitlab.com/ee/ci/",
        type: "documentation",
        difficulty: "INTERMEDIATE",
        estimatedHours: 6,
        platform: "GitLab Official",
        free: true,
        description: "GitLab pipelines and CI/CD workflows",
      },
      {
        title: "Monitoring with Prometheus & Grafana",
        url: "https://www.youtube.com/watch?v=9TJx7QTrTyo",
        type: "course",
        difficulty: "INTERMEDIATE",
        estimatedHours: 4,
        platform: "TechWorld with Nana (YouTube)",
        free: true,
        description: "System monitoring and visualization",
      },
    ],
    advanced: [
      {
        title: "Advanced CI/CD Patterns",
        url: "https://www.youtube.com/watch?v=ym7zDIxjpKE",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "Blue-green deployments, canary releases, feature flags",
      },
      {
        title: "SRE Principles & Practices",
        url: "https://sre.google/books/",
        type: "documentation",
        difficulty: "ADVANCED",
        estimatedHours: 8,
        platform: "Google SRE Books (Free)",
        free: true,
        description: "Google's Site Reliability Engineering principles",
      },
      {
        title: "Cost Optimization for DevOps",
        url: "https://www.youtube.com/watch?v=r0pBlO4h-KY",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours: 2,
        platform: "YouTube",
        free: true,
        description: "Cost-effective infrastructure and automation",
      },
    ],
  },
  practiceResources: [
    {
      title: "Setup Your First GitHub Action Workflow",
      url: "https://docs.github.com/en/actions/quickstart",
      type: "practice",
      difficulty: "BEGINNER",
      estimatedHours: 2,
      platform: "GitHub Official",
      free: true,
      description: "Create your first CI/CD workflow",
    },
    {
      title: "Build a Complete CI/CD Pipeline",
      url: "https://www.youtube.com/watch?v=aoyx-y1ybEE",
      type: "practice",
      difficulty: "INTERMEDIATE",
      estimatedHours: 8,
      platform: "YouTube",
      free: true,
      description: "End-to-end CI/CD with testing and deployment",
    },
    {
      title: "Infrastructure as Code Project",
      url: "https://github.com/topics/iac",
      type: "practice",
      difficulty: "INTERMEDIATE",
      estimatedHours: 10,
      platform: "GitHub",
      free: true,
      description: "Create reproducible infrastructure",
    },
  ],
  projectIdeas: [
    "Setup automated GitHub Actions for your projects",
    "Create a Jenkins CI/CD pipeline",
    "Automate infrastructure provisioning with Terraform",
    "Set up monitoring with Prometheus and Grafana",
    "Implement blue-green deployment strategy",
  ],
}

const FRONTEND_PATH: SkillPath = {
  skillName: "Frontend (React/Vue/Angular)",
  skillCategory: "Frontend",
  overview: "Master modern JavaScript frameworks and frontend best practices",
  learningPath: {
    beginner: [
      {
        title: "HTML & CSS Fundamentals",
        url: "https://www.youtube.com/watch?v=qz0aGYrrlMU",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 5,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "HTML structure, CSS styling, responsive design",
      },
      {
        title: "JavaScript Fundamentals",
        url: "https://www.youtube.com/watch?v=PkZNo7MFNFg",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 4,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "JavaScript basics - variables, functions, DOM",
      },
      {
        title: "React Tutorial for Beginners",
        url: "https://www.youtube.com/watch?v=DLX62G4lc44",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 4,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "React fundamentals - components, JSX, hooks",
      },
      {
        title: "React Official Documentation",
        url: "https://react.dev/",
        type: "documentation",
        difficulty: "BEGINNER",
        estimatedHours: 10,
        platform: "React Official",
        free: true,
        description: "Official React docs with interactive examples",
      },
    ],
    intermediate: [
      {
        title: "React Hooks & State Management",
        url: "https://www.youtube.com/watch?v=TNhaISOUy6Q",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "Advanced hooks, Context API, state management",
      },
      {
        title: "TypeScript for React",
        url: "https://www.youtube.com/watch?v=Z5iWr6Srsj8",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 2,
        platform: "YouTube",
        free: true,
        description: "Type-safe React components with TypeScript",
      },
      {
        title: "Next.js Framework",
        url: "https://www.youtube.com/watch?v=ZVnjOPwW8p8",
        type: "course",
        difficulty: "INTERMEDIATE",
        estimatedHours: 6,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "Next.js - SSR, static generation, API routes",
      },
      {
        title: "Vue.js Tutorial",
        url: "https://www.youtube.com/watch?v=FXY1UyplmWs",
        type: "course",
        difficulty: "INTERMEDIATE",
        estimatedHours: 4,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "Vue.js fundamentals and composition API",
      },
    ],
    advanced: [
      {
        title: "React Performance Optimization",
        url: "https://www.youtube.com/watch?v=WhoCESr5IpI",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "Memoization, code splitting, lazy loading",
      },
      {
        title: "Web Performance Fundamentals",
        url: "https://developers.google.com/web/fundamentals/performance",
        type: "documentation",
        difficulty: "ADVANCED",
        estimatedHours: 6,
        platform: "Google Developers",
        free: true,
        description: "Core Web Vitals, optimization, best practices",
      },
      {
        title: "Web Accessibility (a11y)",
        url: "https://www.youtube.com/watch?v=K87QHwFsrWQ",
        type: "course",
        difficulty: "ADVANCED",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "WCAG standards, accessible components",
      },
    ],
  },
  practiceResources: [
    {
      title: "Build Projects with React",
      url: "https://react.dev/learn/thinking-in-react",
      type: "practice",
      difficulty: "BEGINNER",
      estimatedHours: 10,
      platform: "React Official",
      free: true,
      description: "Step-by-step guide to building React applications",
    },
    {
      title: "Frontend Coding Challenges",
      url: "https://www.frontendmentor.io/",
      type: "practice",
      difficulty: "INTERMEDIATE",
      estimatedHours: 15,
      platform: "Frontend Mentor",
      free: true,
      description: "Design-to-code challenges for frontend practice",
    },
    {
      title: "Open Source React Projects",
      url: "https://github.com/topics/react",
      type: "practice",
      difficulty: "INTERMEDIATE",
      estimatedHours: 12,
      platform: "GitHub",
      free: true,
      description: "Contribute to open source React projects",
    },
  ],
  projectIdeas: [
    "Build a To-Do app with React and localStorage",
    "Create a Weather app with API integration",
    "Build a Portfolio website with Next.js",
    "Create a Real-time Collaborative Editor",
    "Build an E-commerce product list with filtering",
  ],
}

const SOFT_SKILLS_PATH: SkillPath = {
  skillName: "Soft Skills & Communication",
  skillCategory: "Soft Skills",
  overview: "Master communication, leadership, and interpersonal skills for career growth",
  learningPath: {
    beginner: [
      {
        title: "Communication Skills Fundamentals",
        url: "https://www.youtube.com/watch?v=4RoM0Hep5ts",
        type: "course",
        difficulty: "BEGINNER",
        estimatedHours: 4,
        platform: "freeCodeCamp (YouTube)",
        free: true,
        description: "Clear communication, active listening, presentation basics",
      },
      {
        title: "Technical Writing Essentials",
        url: "https://developers.google.com/tech-writing",
        type: "documentation",
        difficulty: "BEGINNER",
        estimatedHours: 3,
        platform: "Google Technical Writing",
        free: true,
        description: "Writing clear technical documentation",
      },
      {
        title: "Public Speaking for Developers",
        url: "https://www.youtube.com/watch?v=0awJ_j_qxwo",
        type: "video",
        difficulty: "BEGINNER",
        estimatedHours: 2,
        platform: "YouTube",
        free: true,
        description: "Overcoming fear, structuring talks, engaging audience",
      },
      {
        title: "Storytelling & Influence",
        url: "https://medium.com/@topics/storytelling",
        type: "article",
        difficulty: "BEGINNER",
        estimatedHours: 4,
        platform: "Medium",
        free: true,
        description: "Using storytelling to influence and persuade",
      },
    ],
    intermediate: [
      {
        title: "Leadership Fundamentals",
        url: "https://ocw.mit.edu/search/",
        type: "course",
        difficulty: "INTERMEDIATE",
        estimatedHours: 6,
        platform: "MIT OpenCourseWare",
        free: true,
        description: "Leadership principles from MIT",
      },
      {
        title: "Conflict Resolution & Negotiation",
        url: "https://www.youtube.com/watch?v=K4lG1hCDkQE",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "Handling disagreements professionally",
      },
      {
        title: "Emotional Intelligence at Work",
        url: "https://dev.to/t/leadership",
        type: "article",
        difficulty: "INTERMEDIATE",
        estimatedHours: 4,
        platform: "Dev.to/Medium",
        free: true,
        description: "Self-awareness, empathy, and relationship management",
      },
      {
        title: "Mentoring & Teaching Others",
        url: "https://www.youtube.com/watch?v=bCG-X-rxRkw",
        type: "video",
        difficulty: "INTERMEDIATE",
        estimatedHours: 2,
        platform: "YouTube",
        free: true,
        description: "Effectively teaching and mentoring teammates",
      },
    ],
    advanced: [
      {
        title: "Executive Presence & Career Leadership",
        url: "https://www.youtube.com/watch?v=h8__WtzN4aY",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours: 3,
        platform: "YouTube",
        free: true,
        description: "Building credibility and influence at higher levels",
      },
      {
        title: "Strategic Communication",
        url: "https://medium.com/t/strategy",
        type: "article",
        difficulty: "ADVANCED",
        estimatedHours: 4,
        platform: "Medium",
        free: true,
        description: "Aligning communication with business strategy",
      },
      {
        title: "Difficult Conversations at Work",
        url: "https://www.youtube.com/watch?v=O2cWLzKmvq8",
        type: "video",
        difficulty: "ADVANCED",
        estimatedHours: 2,
        platform: "YouTube",
        free: true,
        description: "Handling feedback, criticism, and performance conversations",
      },
    ],
  },
  practiceResources: [
    {
      title: "Start a Tech Blog",
      url: "https://dev.to/",
      type: "practice",
      difficulty: "BEGINNER",
      estimatedHours: 10,
      platform: "Dev.to",
      free: true,
      description: "Write articles about your learnings and experiences",
    },
    {
      title: "Give Tech Talks & Presentations",
      url: "https://www.meetup.com/",
      type: "practice",
      difficulty: "INTERMEDIATE",
      estimatedHours: 8,
      platform: "Meetup.com",
      free: true,
      description: "Present at local meetups or conferences",
    },
    {
      title: "Participate in Open Source Communities",
      url: "https://github.com/open-source",
      type: "practice",
      difficulty: "INTERMEDIATE",
      estimatedHours: 10,
      platform: "GitHub",
      free: true,
      description: "Collaborate with others on open source projects",
    },
  ],
  projectIdeas: [
    "Write a technical blog post about a project you built",
    "Give a presentation at a tech meetup",
    "Mentor someone in your area of expertise",
    "Lead a small team or project",
    "Write a technical tutorial or guide",
  ],
}

// ============= SKILL PATHS COLLECTION =============

export const ALL_SKILL_PATHS: Record<string, SkillPath> = {
  "java-core": JAVA_CORE_PATH,
  "spring-framework": SPRING_FRAMEWORK_PATH,
  "microservices": MICROSERVICES_PATH,
  "cloud": CLOUD_PATH,
  "system-design": SYSTEM_DESIGN_PATH,
  "testing": TESTING_PATH,
  "databases": DATABASES_PATH,
  "devops-ci-cd": DEVOPS_CI_CD_PATH,
  "frontend": FRONTEND_PATH,
  "soft-skills": SOFT_SKILLS_PATH,
}

// ============= UTILITY FUNCTIONS =============

/**
 * Get skill path by category name
 */
export function getSkillPath(skillName: string): SkillPath | undefined {
  const key = skillName.toLowerCase().replace(/\s+/g, "-")
  return ALL_SKILL_PATHS[key]
}

/**
 * Get resources by difficulty level
 */
export function getResourcesByDifficulty(
  path: SkillPath,
  difficulty: "BEGINNER" | "INTERMEDIATE" | "ADVANCED"
): LearningResource[] {
  return path.learningPath[difficulty.toLowerCase() as keyof typeof path.learningPath] || []
}

/**
 * Get all resources for a skill (flattened)
 */
export function getAllResources(path: SkillPath): LearningResource[] {
  return [
    ...path.learningPath.beginner,
    ...path.learningPath.intermediate,
    ...path.learningPath.advanced,
    ...path.practiceResources,
  ]
}

/**
 * Get estimated total hours for a skill path
 */
export function estimateTotalHours(path: SkillPath): number {
  const allResources = getAllResources(path)
  return allResources.reduce((sum, resource) => sum + resource.estimatedHours, 0)
}

/**
 * Recommend learning path based on trending skills
 */
export function recommendedSkillPaths(skillNames: string[]): SkillPath[] {
  return skillNames
    .map((skill) => getSkillPath(skill))
    .filter((path): path is SkillPath => path !== undefined)
}
